---
title: "Almond Yield Profit"
author: "Kristin Gill, Yutian Fang, Grace Lewin"
date: "4/19/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
library(tidyverse)
library(janitor)
library(here)
library(lubridate)
library(patchwork)
```

# Import and subset climate data

```{r}
almond_climate_original <- read.table(here("data", "clim.txt")) %>% 
  clean_names()

almond_climate <- almond_climate_original %>% 
  mutate(date = as_date(d)) %>% 
  mutate(year = year(date)) %>%
  mutate(month = month(date))

# temp in february
almond_temp <- almond_climate %>% 
  filter(month == 2) %>% 
  group_by(year) %>%
  summarize(mean_min = mean(tmin_c)) %>% 
  select(year, mean_min)

# precip in january
almond_precip <- almond_climate %>% 
  filter(month == 1) %>% 
  group_by(year) %>% 
  summarize(mean_p = mean(precip), sum_p = sum(precip)) %>% 
  select(year, sum_p)
```

# Import and execute function to estimate almond yield anomalies

```{r}
source(here("R", "almond_yield.R"))

yield <- almond_yield(year = almond_temp$year, p = almond_precip$sum_p, Tn = almond_temp$mean_min)
```

# Profit
```{r}
source(here("R", "compute_NPV.R"))
source(here("R", "almond_profit.R"))

price <- 50

acres <- 1000

base_almonds <- 2000

profit <- compute_profit_almond(yield = yield$almond_yield, year=yield$year, price=price, discount=0.12, acres=acres, base_almonds=base_almonds)
```

#Sensitivity Analysis
```{r}
deviation = 0.15
base_price = 50
base_acres = 1000

price = runif(min = base_price-deviation*base_price,
              max = base_price+deviation*base_price, 
              n = 22)

acres = runif(min = base_acres-deviation*base_acres,
              max = base_acres+deviation*base_acres, 
              n = 22)

parameters = cbind.data.frame(price, acres)

profit_sensitivity = parameters %>% 
  pmap(~compute_profit_almond(yield = yield$almond_yield, year=yield$year, price=.x, discount=0.12, acres=acres, base_almonds=base_almonds))



profit_almonds = map_df(profit_sensitivity,`[`, "total") 

total_profit = cbind.data.frame(profit_almonds, parameters)
```

# Summary figures
```{r, fig.cap="Relationships between the parameters price and almond acres on total profits. From these figures we can see that the number of acres of almonds has the strongest relationship with the total profits."}

#Make scatter plots comparison
p1 = ggplot(total_profit, aes(price, total, col=acres)) +
  geom_point(cex=2) +
  labs(y="Total Annual Profits ($)", x="Almond Acres",
       title = "Relationship Between \nProfit and Acres of Almonds",
       color = "Acres") +
  theme_minimal() +
  scale_color_gradient(low="lightblue", high="darkblue")

p2 = ggplot(total_profit, aes(acres, total, col=price)) +
  geom_point(cex=2) +
  labs(y="Total Annual Profits ($)", x="Price ($)",
       title = "Relationship Between \nProfit and Price of Almonds",
       color = "Price ($)") +
  theme_minimal()+
  scale_color_gradient(low="lightblue", high="darkblue")

p1|p2
```


